### ISSUE TITLE
compiler crash if you add const to main fn prototype

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/zig#191]
```zig
pub fn main(args: [][]const u8) -> %void {}
```

Should be a compile error for putting `const` or for missing `main` function.

Instead causes "LLVM ERROR: Broken module found, compilation aborted!"

Thanks to ofelas on IRC for finding this bug.

**Comment by ofelas** [comment]
`pub fn main(args: [][]constu8) -> %void {` removing the space between `const` and `u8` segfaults zig.

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000007881e6 in buf_ptr (buf=0x8) at ../src/buffer.hpp:36
36	    assert(buf->list.length);
(gdb) bt
#0  0x00000000007881e6 in buf_ptr (buf=0x8) at ../src/buffer.hpp:36
#1  0x000000000078dd7d in preview_fn_proto_instance (g=0x33e6d60, import=0x34188b0, proto_node=0x3419870, containing_context=0x341c6a0)
    at ../src/analyze.cpp:1708
#2  0x000000000078e23d in resolve_top_level_decl (g=0x33e6d60, node=0x3419870, pointer_only=false) at ../src/analyze.cpp:1812
#3  0x0000000000791de3 in analyze_decl_ref (g=0x33e6d60, source_node=0x34341a0, decl_node=0x3419870, pointer_only=false, block_context=0x3440b20, 
    depends_on_compile_var=false) at ../src/analyze.cpp:3136
#4  0x000000000079105a in analyze_field_access_expr (g=0x33e6d60, import=0x3423c10, context=0x3440b20, expected_type=0x0, node=0x34341a0)
    at ../src/analyze.cpp:2844
```

my analyze.cpp is slightly modified with a few;

```
-    zig_panic("TODO");
+    zig_panic("TODO: %s:%s:%d", __FILE__, __func__, __LINE__);
```

**Comment by andrewrk** [comment]
Simpler code snippet to cause first problem:

```zig
fn foo(args: [][]const u8) {}

fn bar(argc: usize) {
    var args: [argc][]u8 = undefined;
    foo(args);
}
```

Second problem is solved locally, will push fix soon.
